name: typstyle formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install typstyle
      run: cargo install typstyle --locked
    - name: Run typstyle on report
      run: typstyle -l 100 --check report/main.typ
    - name: Run typstyle on slide
      run: typstyle -l 100 --check slide/main.typ
